# Generated by Django 5.2.1 on 2025-06-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StakePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.CharField(max_length=100)),
                ('active_stake', models.BigIntegerField()),
                ('live_stake', models.BigIntegerField()),
                ('live_saturation', models.FloatField()),
                ('blocks_minted', models.IntegerField()),
                ('epoch', models.IntegerField()),
                ('url', models.URLField()),
                ('ticker', models.CharField(max_length=9)),
                ('pool_name', models.CharField()),
                ('description', models.TextField(max_length=255)),
                ('homepage', models.URLField()),
            ],
        ),
    ]
