# Generated by Django 5.2.1 on 2025-06-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epoch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='stakepool',
            name='active_stake',
        ),
        migrations.RemoveField(
            model_name='stakepool',
            name='blocks_minted',
        ),
        migrations.RemoveField(
            model_name='stakepool',
            name='epoch',
        ),
        migrations.RemoveField(
            model_name='stakepool',
            name='live_saturation',
        ),
        migrations.RemoveField(
            model_name='stakepool',
            name='live_stake',
        ),
        migrations.RemoveField(
            model_name='stakepool',
            name='pool_name',
        ),
        migrations.AddField(
            model_name='stakepool',
            name='name',
            field=models.CharField(default='Unnamed Pool', max_length=100),
        ),
        migrations.AlterField(
            model_name='stakepool',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stakepool',
            name='pool_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='stakepool',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='StakePoolSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.CharField(max_length=64)),
                ('epoch', models.IntegerField()),
                ('active_stake', models.BigIntegerField()),
                ('live_stake', models.BigIntegerField()),
                ('live_saturation', models.FloatField()),
                ('blocks_minted', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('pool_id', 'epoch')},
            },
        ),
    ]
