# Generated by Django 5.2.1 on 2025-06-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_epoch_end_time_alter_epoch_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoch',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stakepoolsnapshot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
