# Generated by Django 5.2.1 on 2025-06-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_epoch_end_time_alter_epoch_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epoch',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='epoch',
            name='start_time',
        ),
    ]
