"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import logging
from dotenv import load_dotenv
from logging.handlers import TimedRotatingFileHandler, RotatingFileHandler
from pathlib import Path
from decouple import config

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Define log directory inside BASE_DIR. Create if does not exist yet
LOG_DIR = os.path.join(BASE_DIR, 'log')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')

ALLOWED_HOSTS = ['localhost', '127.0.0.1'] # Add 'yourdomain .com' when in production

INTERNAL_IPS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'corsheaders',
    'rest_framework',
    'debug_toolbar'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

ROOT_URLCONF = 'cardano_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cardano_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('DB_DJANGO_NAME'),
        'USER' : os.getenv('DB_DJANGO_USER'),
        'PASSWORD' : os.getenv('DB_DJANGO_PASSWORD'),
        'HOST': os.getenv('DB_DJANGO_HOST'),
        'PORT' : os.getenv('DB_DJANGO_PORT')
    },
    'cardano': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('DB_CARDANO_NAME'),
        'USER' : os.getenv('DB_CARDANO_USER'), # Access to user with select privileges and not owner
        'PASSWORD' : os.getenv('DB_CARDANO_PASSWORD'),
        'HOST': os.getenv('DB_DJANGO_HOST'),
        'PORT' : os.getenv('DB_DJANGO_PORT')
    }
}

DATABASE_ROUTERS = ['cardano_backend.routers.CardanoDBRouter']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-ch'

TIME_ZONE = 'Europe/Zurich'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True # Keep for development only

#CORS_ORIGIN_ALLOW_ALL = False

#CORS_ORIGIN_WHITELIST = ['http://localhost:5173', 'http://localhost:3000', 'http://localhost:8000']


# Allow connection to port of frontend
# CORS_ALLOWED_ORIGINS = [
#    'http://localhost:5173',
# ]

# CORS_ALLOW_CREDENTIALS = True

LOGGING = {
    'version' : 1,
    'disable_existing_loggers': False,
    'formatters': {
        'daily_formatter': {
            'format': '{asctime} {module} {levelname} - {message}', # Output like ERROR - Epoch number should be string
            'style': '{'
        },
        'error_formatter': {
            'format': '{asctime} {module} - {message}', # Output like ERROR - Epoch number should be string
            'style': '{'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'daily_formatter'
        },
        # Handler for daily logs
        'daily_file_handler': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'djang_daily.log'),
            'when': 'midnight', # Rotate at midnight every day
            'interval': 1, # Rotate every 1 day
            'backupCount': 10, # Keep 10 days of backup logs
            'formatter': 'daily_formatter',
            'encoding': 'utf8'
        },
        # Handler for errors only
        'error_file_handler': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'djang_error.log'),
            'maxBytes': 1024 * 1024 * 5, # 5 MB
            'backupCount': 5, # Keep 5 days of backup logs,
            'level': 'ERROR',
            'formatter': 'error_formatter',
            'encoding': 'utf8'
        },
    },
    'loggers': {
        # Root logger
        'django': {
            'handlers': ['daily_file_handler', 'error_file_handler'],
            'level': 'INFO',
            'propagate': True,
        },
        # To show SQL queries
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False
        }
    },
}
